### ISSUE TITLE
MentalBreaker_MentalBreakerTick_Patch Possible Optimization

### ISSUE THREAD

**Issue by kbatbouta** [pardeike/Achtung2#18]
I've noticed that the current patch even with the IsHashIntervalTick is running many times in each tick without the benefits of IsHashIntervalTick thus i did some changes (most of them due to my play style and needs).

Please consider parts of this for a optimization update:

- I used Map.MapPreTick instead of MentalBreaker...

```
    [HarmonyPatch(typeof(Map))]
    [HarmonyPatch(nameof(Map.MapPreTick))]
    static class MentalBreaker_MentalBreakerTick_Patch
    {
        public static bool Prefix(Map __instance)
        {
            if (!Gen.IsHashIntervalTick(Find.FactionManager.OfPlayer, 240))
                return true;
            foreach (Pawn p in BreakRiskAlertUtility.PawnsAtRiskExtreme)
            {

                //BreakRiskAlertUtility.
                if (p.IsColonist == false)
                    continue;

                var forcedWork = Find.World.GetComponent<ForcedWork>();
                if (forcedWork.HasForcedJob(p))
                {
                    p.Map.pawnDestinationReservationManager.ReleaseAllClaimedBy(p);
                    forcedWork.Remove(p);
                    p.jobs?.EndCurrentJob(JobCondition.InterruptForced, true);
                }
            }
            return true;
        }
    }
```

Thank you for your great work!!

**Comment by pardeike** [comment]
That looks odd. It's not a good optimisation because it would have to iterate over all pawn at every map tick.
The current implementation isn't optimal so I can see what I can do to improve it. Can you explain what problem made you suggest the above code? It also skips the health checks compared to the original.

**Comment by pardeike** [comment]
Also, changing to your code seems to change the logic quite a bit and I am worried that it would throw off a lot of users that depend on it as it is now. So, optimizing it is fine, changing the logic isn't.

**Comment by kbatbouta** [comment]
@pardeike sorry for the confusion, been sick for over a week. Currently it just go over pawns with a mental break threshold  over extreme however others can be easily added in an optimized fashion by iterating over the mental break levels over several ticks.

**Comment by kbatbouta** [comment]
And in case of my other "unusual changes" i already have my own code for monitoring health which i'm trying to make all my mod list use it rather than each one setting trigger.

**Comment by pardeike** [comment]
I just tested it with like 50 colonists and any change I made (including increasing 120 to 2400) make barely a difference in fps. I don't think this method has any major effect on your gameplay.

**Comment by kbatbouta** [comment]
@pardeike My Macbook is at the heart of my problems or also known as a potato PC.

**Comment by pardeike** [comment]
Unfortunately, your change does change the logic too much (like for example it includes colonists on all maps and those being in a caravan. For multiple maps it runs everything multiple times.

**Comment by kbatbouta** [comment]
I know just making a note not a bug obviously.
