### ISSUE TITLE
Some texts are not translatable

### ISSUE THREAD

**Issue by Ragnar-F** [pardeike/Achtung2#41]
Specifically:

https://github.com/pardeike/Achtung2/blob/f45f6f7b9b896bb85e24ebc547807e785a016657/Source/ForcedFloatMenuOption.cs#L220

https://github.com/pardeike/Achtung2/blob/f45f6f7b9b896bb85e24ebc547807e785a016657/Source/ForcedJob.cs#L283

https://github.com/pardeike/Achtung2/blob/f45f6f7b9b896bb85e24ebc547807e785a016657/Source/ForcedJob.cs#L310

**Comment by pardeike** [comment]
Thanks for the feedback, I will incorporate the changes in the next release

**Comment by pardeike** [comment]
Fixedin in 0dde5cf01289d234e198700e8c363a8938c7d24b
