### ISSUE TITLE
Request: Option for a 'performance mode' with only formations

### ISSUE THREAD

**Issue by LuxArdens** [pardeike/Achtung2#46]
Currently this seems to be the only Rimworld mod that has a simple way to drag drafted pawns into formations. Unfortunately some of the other functions related to tasking and forced work are a constant drain on TPS even outisde of combat and thus not always desired. 

Could we get an option to disable all the extra functionality, leaving just the drafted positioning/formations?

**Comment by pardeike** [comment]
Please explain the pretty generic “ some of the other functions related to tasking and forced work are a constant drain on TPS ”.

**Comment by pardeike** [comment]
Also, I recommend taking this discussion on my discord as a better way to communicate.

**Comment by LuxArdens** [comment]
I won't pretend to know what exactly it is, since I don't do C#, but I noticed in Dub's performance analyzer that Achtung is making thousands of calls and takes around 2-5 ms per update (in my particular mod load this places it in the top three of heaviest mods) even when no pawns are drafted and I'm using none of the forced work functions. 

Not trying to barge in and make demands or pretend I know things better or anything. I'm just wondering if you could separate the mod's two main functions with either an option in the mod's configuration menu or maybe a "light" version of sorts, because I really like the draft formations but probably will have to remove it from my mod loadout for my optimized late-game bases. I know a lot of other players seek your mod's draft functions above the other stuff. So is it something you could maybe add? Or is it not going to happen?

**Comment by pardeike** [comment]
I prefer to to split up my mods. Makes it more time consuming. I have already put like 20-40 hours in optimization into Achtung and if you mod your game so much that you cannot run Achtung you probably have other problems anyway.

Sorry, I am not going to split up Achtung into several mods. If you don't force stuff it basically does nothing.

**Comment by LuxArdens** [comment]
Okay, well thanks for considering it!
