### ISSUE TITLE
Stopped working as of 11 Mar. 2022

### ISSUE THREAD

**Issue by pardeike** [pardeike/Achtung2#51]
Was working as of 10 Mar. 2022.  As of 11 Mar. 2022 could not use the force build command along with several other features.  Not sure what happened.

-- submitted by bdkenney29@hotmail.com

**Comment by pardeike** [comment]
At this point I can and will only fix bugs that are reproducible with no other mods or with one specific incompatible mod. And not without logs and detailed descriptions of what happens. 

I have tested Achtung with stable and unstable RimWorld and it works as expected.

**Comment by Forkunare** [comment]
Okay, I just want to report that version 3.4.1 dated 14_01_2022 continues to work fine with HSK dated 13_12_2021. I checked.
Perhaps this information will be useful to someone.

**Comment by zakhad** [comment]
@Forkunare It was useful for me as i had noticed it suddenly stopped working. and the only thing that's changed with my setup is the bestmix mod being updated that i'm subscribed too, tried rolling back a version but that didn't fix it so i'm uncertain if it's that mod even causing it, but it's the only thing that's changed with my setup from auto-updates. 

![image](https://user-images.githubusercontent.com/5264667/161469621-e3e636ab-fb7a-4ce8-b949-7b365a03e55a.png)
I'm uncertain if that's the same error you're getting, but that's the one i'm getting.

**Comment by pardeike** [comment]
Has anyone tried to systematically disable the other mods until only Achtung remains? This will certainly find the offending mod.

**Comment by Forkunare** [comment]
@zakhad I'm not a member of the HSK community on Discord.
@pardeike Undoubtedly disabling HSK mods can help identify a conflict with your mod, but it's obviously a very time consuming one. Downloading HSK takes up to 4 minutes =) If I have time, I'll try to find the source of the conflict, but I can't promise.
However, I want to point out that the stable version of HSK has not been updated since December 13, 2021 and has no conflicts with Achtung2 since January 14, 2022. HSK stable also requires rimworld 1.2.3005 released May 2021. Thus, the rest of the components, except for the Achtung2 mod, have not changed.

**Comment by Forkunare** [comment]
Installed the latest version of Achtung2.
When trying to open the command menu (right mouse click) on any building with the ability to force commands, an error occurs:

```
Exception filling window for Verse.FloatMenu: System.NullReferenceException: Object reference not set to an instance of an object
  at AchtungMod.ForcedFloatMenuOption.RenderExtraPartOnGui (UnityEngine.Rect drawRect) [0x00088] in <fbbcb83f4592449c9e71ee8d9fbf88f0>:0 
  at AchtungMod.MultiActions+<>c__DisplayClass16_0.<GetOption>b__12 (UnityEngine.Rect drawRect) [0x00000] in <fbbcb83f4592449c9e71ee8d9fbf88f0>:0 
  at (wrapper dynamic-method) Verse.FloatMenuOption.Verse.FloatMenuOption.DoGUI_Patch1(Verse.FloatMenuOption,UnityEngine.Rect,bool,Verse.FloatMenu)
  at Verse.FloatMenu.DoWindowContents (UnityEngine.Rect rect) [0x000fb] in <7927e938de4c4089b4add4215e58d5b1>:0 
  at Verse.Window.InnerWindowOnGUI (System.Int32 x) [0x00165] in <7927e938de4c4089b4add4215e58d5b1>:0 
Verse.Log:Verse.Log.Error_Patch3(String, Boolean)
Verse.Window:InnerWindowOnGUI(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)
```
full log, if you want to sort it out.:
https://pastebin.com/F2JNVHuE

**Comment by pardeike** [comment]
Due to laziness on my part, I broke backwards compatibility with RimWorld 1.2 in one of the previous commits / versions. 

I have no plans to keep 1.2 support up anymore. Life goes on.
