### ISSUE TITLE
I got this error and it told me to submit it so here it is IDK if its helfpull at all.

### ISSUE THREAD

**Issue by HeraldOfTzeentch** [pardeike/Achtung2#58]
Exception in RimWorld.FloatMenuMakerMap.ChoicesAtFor: System.NullReferenceException: Object reference not set to an instance of an object
  at AlphaMemes.RitualObligationTarget_DreadnoughtCorpseStillValid.CanUseTarget (Verse.TargetInfo target, RimWorld.RitualObligation obligation) [0x0004b] in <e3862c0fdfde493689091596099c84cc>:0 
  at AlphaMemes.RitualObligationTargetWorker_FuneralThingExtended.CanUseTargetInternal (Verse.TargetInfo target, RimWorld.RitualObligation obligation) [0x000fa] in <e3862c0fdfde493689091596099c84cc>:0 
  at RimWorld.RitualObligationTargetFilter.CanUseTarget (Verse.TargetInfo target, RimWorld.RitualObligation obligation) [0x0001f] in <81af9f8a18324e17b286924a43555a7c>:0 
  at RimWorld.Precept_Ritual.CanUseTarget (Verse.TargetInfo target, RimWorld.RitualObligation obligation) [0x00000] in <81af9f8a18324e17b286924a43555a7c>:0 
  at Verse.Thing+<GetFloatMenuOptions>d__147.MoveNext () [0x0020e] in <81af9f8a18324e17b286924a43555a7c>:0 
  at Verse.ThingWithComps+<GetFloatMenuOptions>d__40.MoveNext () [0x00078] in <81af9f8a18324e17b286924a43555a7c>:0 
  at RimWorld.FloatMenuMakerMap.AddHumanlikeOrders (UnityEngine.Vector3 clickPos, Verse.Pawn pawn, System.Collections.Generic.List`1[T] opts) [0x04679] in <81af9f8a18324e17b286924a43555a7c>:0 
     - transpiler CombatExtended.HarmonyCE: IEnumerable`1 CombatExtended.HarmonyCE.FloatMenuMakerMap_Modify_AddHumanlikeOrders:Transpiler(IEnumerable`1 instructions)
     - transpiler PerformanceOptimizer.Main: IEnumerable`1 PerformanceOptimizer.Optimization_FasterGetCompReplacement:Transpiler(IEnumerable`1 instructions, MethodBase method)
     - prefix rimworld.rwmods.androidtiers: Boolean MOARANDROIDS.FloatMenuMakerMap_Patch+AddHumanlikeOrders_Patch:ListenerPrefix(Vector3 clickPos, Pawn pawn, List`1 opts)
     - prefix com.BioReactor.rimworld.mod: Boolean BioReactor.BioReactorPatches:Prefix_AddHumanlikeOrders(Vector3 clickPos, Pawn pawn, List`1 opts)
     - prefix me.lubar.VanillaExpandedPatches: Void BenLubarsVanillaExpandedPatches.FloatMenuMakerMap_AddHumanlikeOrders_Patch:Prefix(Pawn pawn)
     - postfix OskarPotocki.VFECore: Void VFECore.Patch_FloatMenuMakerMap+AddHumanlikeOrders_Fix:Postfix(Vector3 clickPos, Pawn pawn, List`1& opts)
     - postfix CombatExtended.HarmonyCE: Void CombatExtended.HarmonyCE.FloatMenuMakerMap_Modify_AddHumanlikeOrders:AddMenuItems(Vector3 clickPos, Pawn pawn, List`1 opts)
     - postfix VanillaExpanded.VFEA: Void VFEAncients.HarmonyPatches.BuildingPatches:AddCarryJobs(List`1 opts, Vector3 clickPos, Pawn pawn)
     - postfix com.MedPod.patches: Void MedPod.Patches.Harmony_FloatMenuMakerMap_OverrideRescueWithMedPodVersion:Postfix(Vector3 clickPos, Pawn pawn, List`1& opts)
     - postfix PeteTimesSix.SimpleSidearms: Void PeteTimesSix.SimpleSidearms.Intercepts.FloatMenuMakerMap_AddHumanLikeOrders_Postfix:AddHumanlikeOrders(Vector3 clickPos, Pawn pawn, List`1 opts)
     - postfix legodude17.reloading: Void Reloading.ReloadingFloatMenuAdder:AddWeaponReloadOrders(List`1 opts, Vector3 clickPos, Pawn pawn)
     - postfix legodude17.mvcf: Void MVCF.Harmony.Brawlers:AddHumanlikeOrders_Postfix(List`1 opts, Vector3 clickPos, Pawn pawn)
     - postfix OskarPotocki.HeavyWeapons: Void HeavyWeapons.Patch_FloatMenuMakerMap+AddHumanlikeOrders_Fix:Postfix(Vector3 clickPos, Pawn pawn, List`1& opts)
     - postfix com.alphamemes: Void AlphaMemes.AlphaMemes_FloatMenuMakerMap_AddHumanlikeOrders_Patch:AddDragRelicToAltar(Vector3 clickPos, Pawn pawn, List`1& opts)
     - postfix jecstools.jecrell.humanlikeorders: Void JecsTools._HumanlikeOrdersUtility:AddHumanlikeOrders_PostFix(Vector3 clickPos, Pawn pawn, List`1 opts)
     - postfix rimworld.rwmods.androidtiers: Void MOARANDROIDS.FloatMenuMakerMap_Patch+AddHumanlikeOrders_Patch:ListenerPostfix(Vector3 clickPos, Pawn pawn, List`1 opts)
     - postfix rimworld.kayesh.corpsechildren: Void CorpseChildren.HarmonyPatches:AddHumanlikeOrders_CorpseChildren_Postfix(Vector3 clickPos, Pawn pawn, List`1 opts)
     - postfix InfiniteReinforce: Void InfiniteReinforce.Rimworld_Patch_AddHumanlikeOrders:Postfix(Vector3 clickPos, Pawn pawn, List`1 opts)
     - postfix com.o21toolbox.rimworld.mod: Void O21Toolbox.HarmonyPatches.Harmony_Apparel+AddHumanlikeOrdersPostfix:Postfix(List`1& opts, Pawn pawn, Vector3 clickPos)
     - postfix o21toolbox.neronix17.humanlikeorders: Void O21Toolbox.Utility.HumanlikeOrdersUtility+_HumanlikeOrdersUtility:AddHumanlikeOrders_PostFix(Vector3 clickPos, Pawn pawn, List`1 opts)
     - postfix rimworld.rimquest: Void RimQuest.HarmonyPatches:AddHumanlikeOrders(Vector3 clickPos, Pawn pawn, List`1 opts)
     - postfix Altered.Carbon: Void AlteredCarbon.FloatMenuMakerMap_Patch+AddHumanlikeOrders_Patch:Postfix(Vector3 clickPos, Pawn pawn, List`1& opts)
     - postfix eagle0600.dressPatients: Void DressPatient.Order_DressPatientOrCorpse:DressPatientFloatMenuOption(Vector3 clickPos, Pawn pawn, List`1 opts)
     - postfix me.lubar.VanillaExpandedPatches: Void BenLubarsVanillaExpandedPatches.FloatMenuMakerMap_AddHumanlikeOrders_Patch:Postfix()
     - postfix Roolo.DualWield: Void DualWield.Harmony.FloatMenuMakerMap_AddHumanlikeOrders:Postfix(Vector3 clickPos, Pawn pawn, List`1& opts)
     - postfix com.calltradeships.rimworld.mod: Void CallTradeShips.Patch_FloatMenuMakerMap_AddHumanlikeOrders:Postfix(Vector3 clickPos, Pawn pawn, List`1 opts)
  at RimWorld.FloatMenuMakerMap.ChoicesAtFor (UnityEngine.Vector3 clickPos, Verse.Pawn pawn, System.Boolean suppressAutoTakeableGoto) [0x00109] in <81af9f8a18324e17b286924a43555a7c>:0 
     - prefix com.spdskatr.projectrimfactory: Boolean ProjectRimFactory.Common.HarmonyPatches.Patch_FloatMenuMakerMap_ChoicesAtFor:Prefix(Vector3 clickPos, Pawn pawn, List`1& __result)
     - postfix OskarPotocki.VFECore: Void VFE.Mechanoids.HarmonyPatches.FloatMenuMakerMap_ChoicesAtFor_Patch:Postfix(List`1& __result, Vector3 clickPos, Pawn pawn, Boolean suppressAutoTakeableGoto)
     - postfix net.pardeike.rimworld.mods.achtung: Void AchtungMod.FloatMenuMakerMap_ChoicesAtFor_Postfix:Postfix(List`1 __result, Vector3 clickPos, Pawn pawn)
     - postfix roolo.whatthehack: Void WhatTheHack.Harmony.FloatMenuMakerMap_ChoicesAtFor:Postfix(Vector3 clickPos, Pawn pawn, List`1& __result)
     - postfix roolo.giddyuprideandroll: Void GiddyUpRideAndRoll.Harmony.FloatMenuMakerMap_ChoicesAtFor:Postfix(Vector3 clickPos, Pawn pawn, List`1& __result)
     - finalizer net.pardeike.rimworld.mods.achtung: Exception AchtungMod.FloatMenuMakerMap_ChoicesAtFor_Finalizer:Finalizer(Exception __exception, List`1& __result)

**Comment by HeraldOfTzeentch** [comment]
From what i can Guess its most likely related to the dreadnought funeral ive got in my ideoligeon wich is form VE Pirates and alpha memes i think ill just dont run achtung to be sure for now as thats less likely to brick my save file still a great mod hope this helps

**Comment by pardeike** [comment]
Not an Achtung problem.
