### ISSUE TITLE
maybe old issue?Producing munu error

### ISSUE THREAD

**Issue by Sissidark** [pardeike/Achtung2#65]
![RimworldModError](https://user-images.githubusercontent.com/92515662/198979756-3a0d9626-5b95-408f-9c63-cd0a4a81372b.png)
this is info by right-click copied:
[Log.txt](https://github.com/pardeike/Achtung2/files/9899969/Log.txt)
this is full hormany log:
[https://wormhole.app/YW0WN#L2KcYCaWlCpOp2HV9IMirQ](steam://openurl_external/https://steamcommunity.com/linkfilter/?url=https://wormhole.app/YW0WN#L2KcYCaWlCpOp2HV9IMirQ)

**Comment by pardeike** [comment]
Not an Achtung problem.
