### ISSUE TITLE
Suggestion: Hunger/Sleep/Recreation % level for stopping a given Achtung job.

### ISSUE THREAD

**Issue by kainasmainas** [pardeike/Achtung2#66]
So currently we have ["Mental break level for jobs"](https://i.imgur.com/Cwq6ZXu.png) , but I was wondering if we could also get 3 options(all toggleable) for also Hunger/Sleep/Recreation levels so I could stop the jobs when they're for example at 20% hunger or sleep level.

**Comment by pardeike** [comment]
That's too close to vanilla. The point of forcing is that you really want something to be done. If you want the game to stop it for X then use vanilla orderered jobs.
