### ISSUE TITLE
Performance Degradation. v3.8.1

### ISSUE THREAD

**Issue by xsoalokinx** [pardeike/Achtung2#68]
With the latest update of v3.8.1 my FPS has actually gone down significantly by about 15-20 fps.
Tested in debug mode, without any other mods Dev Quick Test. Using the latest version of Rimworld on Windows 10.
Also took a look in dubs performance analyzer under harmony patches and the latency there is huge. Let me know how I can be of further help, thanks.

**Comment by pardeike** [comment]
Probably fixed in 3.8.2
