### ISSUE TITLE
Ignore Forbidden Markings also ignores zone restrictions

### ISSUE THREAD

**Issue by AerosAtar** [pardeike/Achtung2#69]
Rimworld: 1.4.3901 rev238 (+ Royalty, Ideology, Biotech)
Harmony: Lib 2.2.2.0 / Mod 1.5.0.0
Achtung: 3.8.7
AlllYourBase.
No other mods.

# Steps To Reproduce

1. Enable option "Ignore Forbidden Markings", ensuring "Ignore Zone Restrictions" is **disabled**.
2. Start new game / Dev quicktest.
3. Create small stockpile zone to ensure hauling is possible.
4. Create zone that excludes one or more forbidden item stacks.
5. Assign test colonist to zone from step 4.
6. Select the test colonist and right-click a forbidden item stack that is **inside** the permitted zone for the colonist.
7. Select the test colonist and right-click a forbidden item stack that is **outside** the permitted zone for the colonist.

# Expected Behaviour

- Right-click menu for the item stack ***inside*** the permitted zone displays as normal and permits issuing of 'prioritize...' instructions.
- Right-click menu for the item stack ***outside*** the permitted zone displays "outside permitted area", as per vanilla behaviour.

# Actual Behaviour

- :heavy_check_mark: Right-click menu for the item stack ***inside*** the permitted zone displays as normal and permits issuing of 'prioritize...' instructions.
- :x: Right-click menu for the item stack ***outside*** the permitted zone displays as normal and permits issuing of 'prioritize...' instructions.

# Debug Log
Command line arguments: -popupwindow
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Message (string)
Verse.Root:CheckGlobalInit ()
Verse.Root:Start ()
Verse.Root_Entry:Start ()

RimWorld 1.4.3901 rev238
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Message (string)
RimWorld.VersionControl:LogVersionNumber ()
Verse.Root:CheckGlobalInit ()
Verse.Root:Start ()
Verse.Root_Entry:Start ()

Achtung v3.8.7.0 Info: To make Achtung log some performance info, create an empty 'AchtungPerformance.txt' file in same directory as Player.log
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Message (string)
AchtungMod.World_FinalizeInit_Patch:Prefix ()
(wrapper dynamic-method) RimWorld.Planet.World:RimWorld.Planet.World.FinalizeInit_Patch1 (RimWorld.Planet.World)
RimWorld.Planet.WorldGenerator:GenerateWorld (single,string,RimWorld.Planet.OverallRainfall,RimWorld.Planet.OverallTemperature,RimWorld.Planet.OverallPopulation,System.Collections.Generic.List`1<RimWorld.FactionDef>,single)
Verse.Root_Play:SetupForQuickTestPlay ()
RimWorld.MainMenuDrawer/<>c:<DoMainMenuControls>b__18_13 ()
Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__27_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()

Initializing new game with mods:
  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - Ludeon.RimWorld.Ideology
  - Ludeon.RimWorld.Biotech
  - brrainz.achtung
  - Mehni.AllYourBase
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Message (string)
Verse.Game:InitNewGame ()
Verse.Root_Play/<>c:<Start>b__1_2 ()
Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__27_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()

**Comment by pardeike** [comment]
Expected behaviour. The settings should be seen as THIS or THIS or THIS. Which means as soon as at least one of the condition is true (outside of allowed zone, forbidden) and you issue a command on it, you can do it. This avoids confusion as at least one condition is met and users often do not realize that the complex combinations hinder them from doing things.

In the end its more of a convenience. You can allow things that other would not be possible and the final decision is up to the user issuing the command.

**Comment by pardeike** [comment]
PS: I will not remodel the code to follow the complex combinations of settings as it is already a pain to offer this functionailty while at the same time be efficient with it and patching the different areas of game code that are spread all over the place. There is no simple method that contains the logic in one place.

**Comment by AerosAtar** [comment]
OK, that makes sense then. Just a miscommunication/misunderstanding due to how other mods often handle things. I'm certainly not going to demand you change things, I simply raised the issue due to it not working how I understood it should. Since that understanding was actually in error, there is no issue. :)
