### ISSUE TITLE
Request: additional option to turn some stuff off

### ISSUE THREAD

**Issue by LuxArdens** [pardeike/Achtung2#71]
Hi, first off: thanks for your continued work on this mod. 

Ever since updating from 1.3 I have tried to get used to the left-click behaviour where left-clicking automatically selects additional pawns and moves them around, and the right click, drag and drop attack stuff. 

I don't like it at all though. I'd like to request the ability to turn this behaviour off in the mod settings. To clarify I mean all the stuff that happens when the cursor becomes either a set of green arrows or a target icon, that I guess was added at some point between Rimworld 1.3 and 1.5.

###
Reason I don't like them, just in case that is useful info: I love literally all the other functions, but these don't seem useful unless perhaps if you only use a mouse and no keyboard shortcuts. E.g.:
- you can't deselect a drafted pawn with left-click, 
- there is already the Shift+click option to (de-)select specific pawns/whatever in vanilla, which is just as fast
- you cannot select anything below a drafted pawn. If there is a downed pawn beneath a drafted one, you cannot click on it at all. 
- Using the melee or ranged attack hotkey, you can already have selected pawns attack an enemy without having to perfectly right click one and then drag drop to an enemy. The vanilla method is physically faster and arguably harder to miss click.
###

**Comment by LuxArdens** [comment]
Addendum: for some reason the selection box of drafted pawns is also much larger that the tile itself, so it is very hard to select anything next to them at all.

**Comment by pardeike** [comment]
You are talking about the preview, right? There is no official release yet. I try to keep this Issues feature for bug reports but on an experimental feature it’s too early and cumbersome as a communications channel. My Achtung channel on my discord is better for rapid feedback during prototyping.
