### ISSUE TITLE
Achtung! Removes Mech Paramedics Ability to rescue pawns

### ISSUE THREAD

**Issue by CrazySnapDragon** [pardeike/Achtung2#76]
Just as the title says, I can't provide any logs because there's no errors, but basically with Achtung! on, Biotech Paramedics Are unable to rescue downed colonists, With Achtung! Added, In Paramedics Work Activities:

-Rescue Downed Allies To Bed

Line disappears, meaning Paramedics can't rescue, only tend and extinguish fires

This is how it looks with Achtung! on:
![image](https://github.com/pardeike/Achtung2/assets/62919054/704b5871-fa22-4be7-a15d-c4be1c63c344)

This is without Achtung!:
![image](https://github.com/pardeike/Achtung2/assets/62919054/d93e7df6-be97-4dcf-aa28-038fb1c6fcbc)

**Comment by pardeike** [comment]
Have you tried to turn off the custom rescue work type in Achtung?

**Comment by CrazySnapDragon** [comment]
Turning off custom rescue work type in the settings fixes the issue! Thank you for the quick reply!
